FROM docker.io/library/node:22-bookworm

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    git \
    golang-go \
    jq \
    make \
    python3 \
    python3-pip \
    python3-venv \
    shellcheck \
    yq \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
